name: CI - clone app and test execution on

permissions:
  contents: read

on:
  push:
    branches: [ "CICD"]
  pull_request:
    branches: ["CICD"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: 6007
      VITE_API_URL: http://localhost:6007/api

    steps:
      - name: checkout actuality repo
        uses: actions/checkout@v3

      - name: clone repo athenea
        run: |
          git clone https://github.com/Atenea-Conocimientos/redux-athena-bank.git

      - name: create .env file backend
        run: |
          cd redux-athena-bank/app/backend
          printf '%s\n' "MONGO_URI=${MONGO_URI}" > .env
          printf '%s\n' "JWT_SECRET=${JWT_SECRET}" >> .env
          printf '%s\n' "PORT=${PORT}" >> .env
          printf '%s\n' "VITE_API_URL=${VITE_API_URL}" >> .env

      - name: install dependencies backend
        run: |
          cd redux-athena-bank/app/backend
          npm install

      - name: Construct backend
        run: |
          cd redux-athena-bank/app/backend
          npm run dev > backend.log 2>&1 &

      - name: install wait-on
        run: |
          npm install -g wait-on

      - name: Backend
        run: wait-on tcp:6007

      - name: install dependencies frontend
        run: |
          cd redux-athena-bank/app/frontend
          npm install
        env:
          VITE_API_URL: ${{ env.VITE_API_URL }}

      - name: Construct frontend
        run: wait-on http://localhost:3000